import type { Metadata } from 'next';
import '@/styles/globals.css';
import HeaderNavigation from '@/components/common/HeaderNavigation';
import ThemeProvider from '@/components/common/ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className="mx-auto max-w-4xl px-8 lg:max-w-2xl">
        <ThemeProvider>
          <HeaderNavigation />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
